name: Sync to GCS Bucket

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch

jobs:
  sync-to-gcs:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Authenticate with Google Cloud
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: your-gcp-project-id  # Replace with your GCP Project ID

      # Sync the files to the GCS bucket, excluding specific files
      - name: Sync Files to GCS
        run: |
          # Install google-cloud-cli
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli

          # Sync repository files to the GCS bucket, excluding license, readme, and JSON files
          gsutil -m rsync -r -x "(?i)^(LICENSE|README.*|.*\.json)$" . gs://osd-scripts  # Replace with your GCS bucket name
